/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'updateProduct' : IDL.Func([Product], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'updateProduct' : IDL.Func([Product], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };